lib/robotica_face_web/router.ex
defmodule RoboticaFaceWeb.Router do
  use RoboticaFaceWeb, :router

  @api_username Application.get_env(:robotica_face, :api_username)
  @api_password Application.get_env(:robotica_face, :api_password)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug RoboticaFace.Auth.CheckLoginToken
  end

  pipeline :ensure_auth do
    plug RoboticaFace.Auth.EnsureAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug BasicAuth, username: @api_username, password: @api_password
  end

  scope "/", RoboticaFaceWeb do
    pipe_through :browser
    pipe_through :auth

    get "/", PageController, :index
    get "/login", SessionController, :index
    post "/login", SessionController, :login
    post "/logout", SessionController, :logout
  end

  scope "/", RoboticaFaceWeb do
    pipe_through :browser
    pipe_through :auth
    pipe_through :ensure_auth

    scope "/schedule" do
      get "/", ScheduleController, :upcoming_list
    end
  end

  scope "/api", RoboticaFaceWeb do
    pipe_through :api

    post "/", ApiController, :index
  end
end

lib/robotica_face_web/views/layout_view.ex
defmodule RoboticaFaceWeb.LayoutView do
  use RoboticaFaceWeb, :view
end

lib/robotica_face_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>RoboticaFace · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
          <%= if RoboticaFace.Auth.user_signed_in?(@conn) do %>
            <li><strong><%= RoboticaFace.Auth.current_user(@conn)["name"] %></strong></li>
            <li><%= link "Logout", to: Routes.session_path(@conn, :logout), method: :post%></li>
          <% else %>
            <li><a href="<%= Routes.session_path(@conn, :index) %>">Login</a></li>
          <% end %>
          </ul>
        </nav>
        <a href="/" class="logo">
          Robotica
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>